spring.application.name=HoCom

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.xvogazjnqddlrqoxzale
spring.datasource.password=this@is#the$


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=YourSuperSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong!!
jwt.expiration=86400000

# Cloudinary Configuration
cloudinary.cloud-name=ddmog9gmh
cloudinary.api-key=517361626893892
cloudinary.api-secret=-LYDcjbhOjoHP1mLDZoWaOBugkc